/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Star.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Star(props) {
  const { nodes, materials } = useGLTF('./models/Star.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.star.geometry} material={materials.None} />
    </group>
  )
}

useGLTF.preload('./models/Star.glb')
